#!/usr/bin/with-contenv bash

if [ "$TVGUIDE_EPG" = "TRUE" ]; then
  echo "[ZAP2XML] Using TVGuide instead of Zap2it for EPG XML"
  ZAP2XML_ARGS="$ZAP2XML_ARGS -z"
fi

echo "[ZAP2XML] Updating EPG XML..."
(crontab -l ; echo "0 */$XML_UPDATE_INTERVAL * * * perl /app/zap2xml.pl -u "$ZAP2XML_USERNAME" -p "$ZAP2XML_PASSWORD" -U -o "/data/$XMLTV_FILENAME" $ZAP2XML_ARGS >> /var/log/cron.log; echo "[ZAP2XML] XML EPG has been updated!"") | crontab -
(perl /app/zap2xml.pl -u "$ZAP2XML_USERNAME" -p "$ZAP2XML_PASSWORD" -U -o "/data/$XMLTV_FILENAME" $ZAP2XML_ARGS >> /var/log/cron.log; echo "[ZAP2XML] XML EPG has been updated!") &
