#!/usr/bin/with-contenv bash

if [ "$TVGUIDE_EPG" = "TRUE" ]; then
  echo "[ZAP2XML] Using TVGuide instead of Zap2it for EPG XML"
  ZAP2XML_ARGS="$ZAP2XML_ARGS -z"
fi

zap2xml='echo $(date) [ZAP2XML] XML EPG is being updated\!; perl /app/zap2xml.pl -u "$ZAP2XML_USERNAME" -p "$ZAP2XML_PASSWORD" -U -o "/data/$XMLTV_FILENAME" $ZAP2XML_ARGS >> /var/log/cron.log; echo $(date) [ZAP2XML] XML EPG has been updated\!'
echo "0	*/$XML_UPDATE_INTERVAL	*	*	*	$zap2xml" > /etc/crontabs/abc
eval {$zap2xml} &
